name: Azure CI CD Pipeline Simulation

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build
        run: echo "Building application..."

      - name: Run Deploy
        run: echo "Deploying application to Azure..."
